/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"

namespace ScillSDK
{

/*
 * ScillApiBattlePassLevelId
 *
 * Used in previous versions of the battle pass system to provide the level_id via payload. We changed routes in newer versions to have level id in the path.
 */
class SCILLSDK_API ScillApiBattlePassLevelId : public Model
{
public:
    virtual ~ScillApiBattlePassLevelId() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The level id, i.e. battle_pass_level_id of the BattlePassLevel object */
	FString BattlePassLevelId;
};

}
