/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"
#include "ScillApiLeaderboardV2MemberTypeRanking.h"

namespace ScillSDK
{

/*
 * ScillApiLeaderboardV2ResultsLeaderboardResultsByMemberType
 *
 * This object uses two keys - \&quot;user\&quot; and \&quot;team\&quot;, both of which contain ranking info
 */
class SCILLSDK_API ScillApiLeaderboardV2ResultsLeaderboardResultsByMemberType : public Model
{
public:
    virtual ~ScillApiLeaderboardV2ResultsLeaderboardResultsByMemberType() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<ScillApiLeaderboardV2MemberTypeRanking> Team;
	TOptional<ScillApiLeaderboardV2MemberTypeRanking> User;
};

}
