/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"
#include "ScillApiChallenge.h"

namespace ScillSDK
{

/*
 * ScillApiChallengeCategory
 *
 * Challenges are grouped into categories. You can exclude or include categories in queries. Per default all categories will be returned.
 */
class SCILLSDK_API ScillApiChallengeCategory : public Model
{
public:
    virtual ~ScillApiChallengeCategory() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Indicates if this is the daily category, bringing up new challenges every day for the user to tackle. */
	TOptional<bool> IsDailyCategory;
	/* In the admin panel you set the order of the categories. This is the position index and indicates the position within the categories array. */
	TOptional<int32> CategoryPosition;
	/* A short name without special chars to make it easier to refer to a specific category (in code) that is language and id agnostic. */
	TOptional<FString> CategorySlug;
	/* The name of the category in the local language set as the query parameter. */
	TOptional<FString> CategoryName;
	/* Indicates how many “tasks” must be completed or done to complete this challenge. */
	TOptional<FString> CategoryId;
	/* An array of Challenge objects. */
	TOptional<TArray<ScillApiChallenge>> Challenges;
};

}
