/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"
#include "ScillApiLeaderboardV2MemberMetadata.h"
#include "ScillApiUserInfo.h"

namespace ScillSDK
{

/*
 * ScillApiLeaderboardV2Member
 *
 * The ranking for the user or team in the leaderboard
 */
class SCILLSDK_API ScillApiLeaderboardV2Member : public Model
{
public:
    virtual ~ScillApiLeaderboardV2Member() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The id of the user - its the same user id you used to create the access token and the same user id you used to send the events */
	TOptional<FString> MemberId;
	/* Indicates what type this entry is, it's either user or team */
	TOptional<FString> MemberType;
	/* The score achieved as an integer value. If you want to store floats, for example laptimes you need to convert them into an int before (i.e. multiply by 100 to get hundreds of seconds and format back to float in UI) */
	TOptional<int32> Score;
	/* The position within the leaderboard */
	TOptional<int32> Rank;
	/* Returns an array of the LeaderboardMemberMetadata objects containing user ranking metadata information */
	TOptional<TArray<ScillApiLeaderboardV2MemberMetadata>> MetadataResults;
	TOptional<ScillApiUserInfo> AdditionalInfo;
};

}
