/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"

namespace ScillSDK
{

/*
 * ScillApiLeaderboardInfo
 *
 * The Leaderboard object contains information about the leaderboard itself like the name and the id
 */
class SCILLSDK_API ScillApiLeaderboardInfo : public Model
{
public:
    virtual ~ScillApiLeaderboardInfo() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The id of the app */
	TOptional<FString> AppId;
	/* The id of the leaderboard */
	TOptional<FString> LeaderboardId;
	/* The name of the leaderboard */
	TOptional<FString> Name;
	/* The event type that triggers this leaderboard */
	TOptional<FString> EventType;
	/* True if this leaderboard sorts the score ascending or false if the ranking is defined by a descending score. */
	TOptional<bool> SortOrderAscending;
};

}
