/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "ScillApiWrapper/ScillApiBaseModel.h"

namespace ScillSDK 
{

class SCILLSDK_API ScillApiChallengesApi
{
public:
	ScillApiChallengesApi();
	~ScillApiChallengesApi();

	void SetURL(const FString& Url);
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	class ActivatePersonalChallengeRequest;
	class ActivatePersonalChallengeResponse;
	class CancelPersonalChallengeRequest;
	class CancelPersonalChallengeResponse;
	class ClaimPersonalChallengeRewardRequest;
	class ClaimPersonalChallengeRewardResponse;
	class GenerateWebsocketAccessTokenRequest;
	class GenerateWebsocketAccessTokenResponse;
	class GetActivePersonalChallengesRequest;
	class GetActivePersonalChallengesResponse;
	class GetAllPersonalChallengesRequest;
	class GetAllPersonalChallengesResponse;
	class GetPersonalChallengeByIdRequest;
	class GetPersonalChallengeByIdResponse;
	class GetPersonalChallengesRequest;
	class GetPersonalChallengesResponse;
	class GetUnresolvedPersonalChallengesRequest;
	class GetUnresolvedPersonalChallengesResponse;
	class UnlockPersonalChallengeRequest;
	class UnlockPersonalChallengeResponse;
	
    DECLARE_DELEGATE_OneParam(FActivatePersonalChallengeDelegate, const ActivatePersonalChallengeResponse&);
    DECLARE_DELEGATE_OneParam(FCancelPersonalChallengeDelegate, const CancelPersonalChallengeResponse&);
    DECLARE_DELEGATE_OneParam(FClaimPersonalChallengeRewardDelegate, const ClaimPersonalChallengeRewardResponse&);
    DECLARE_DELEGATE_OneParam(FGenerateWebsocketAccessTokenDelegate, const GenerateWebsocketAccessTokenResponse&);
    DECLARE_DELEGATE_OneParam(FGetActivePersonalChallengesDelegate, const GetActivePersonalChallengesResponse&);
    DECLARE_DELEGATE_OneParam(FGetAllPersonalChallengesDelegate, const GetAllPersonalChallengesResponse&);
    DECLARE_DELEGATE_OneParam(FGetPersonalChallengeByIdDelegate, const GetPersonalChallengeByIdResponse&);
    DECLARE_DELEGATE_OneParam(FGetPersonalChallengesDelegate, const GetPersonalChallengesResponse&);
    DECLARE_DELEGATE_OneParam(FGetUnresolvedPersonalChallengesDelegate, const GetUnresolvedPersonalChallengesResponse&);
    DECLARE_DELEGATE_OneParam(FUnlockPersonalChallengeDelegate, const UnlockPersonalChallengeResponse&);
    
    bool ActivatePersonalChallenge(const ActivatePersonalChallengeRequest& Request, const FActivatePersonalChallengeDelegate& Delegate = FActivatePersonalChallengeDelegate()) const;
    bool CancelPersonalChallenge(const CancelPersonalChallengeRequest& Request, const FCancelPersonalChallengeDelegate& Delegate = FCancelPersonalChallengeDelegate()) const;
    bool ClaimPersonalChallengeReward(const ClaimPersonalChallengeRewardRequest& Request, const FClaimPersonalChallengeRewardDelegate& Delegate = FClaimPersonalChallengeRewardDelegate()) const;
    bool GenerateWebsocketAccessToken(const GenerateWebsocketAccessTokenRequest& Request, const FGenerateWebsocketAccessTokenDelegate& Delegate = FGenerateWebsocketAccessTokenDelegate()) const;
    bool GetActivePersonalChallenges(const GetActivePersonalChallengesRequest& Request, const FGetActivePersonalChallengesDelegate& Delegate = FGetActivePersonalChallengesDelegate()) const;
    bool GetAllPersonalChallenges(const GetAllPersonalChallengesRequest& Request, const FGetAllPersonalChallengesDelegate& Delegate = FGetAllPersonalChallengesDelegate()) const;
    bool GetPersonalChallengeById(const GetPersonalChallengeByIdRequest& Request, const FGetPersonalChallengeByIdDelegate& Delegate = FGetPersonalChallengeByIdDelegate()) const;
    bool GetPersonalChallenges(const GetPersonalChallengesRequest& Request, const FGetPersonalChallengesDelegate& Delegate = FGetPersonalChallengesDelegate()) const;
    bool GetUnresolvedPersonalChallenges(const GetUnresolvedPersonalChallengesRequest& Request, const FGetUnresolvedPersonalChallengesDelegate& Delegate = FGetUnresolvedPersonalChallengesDelegate()) const;
    bool UnlockPersonalChallenge(const UnlockPersonalChallengeRequest& Request, const FUnlockPersonalChallengeDelegate& Delegate = FUnlockPersonalChallengeDelegate()) const;
    
private:
    void OnActivatePersonalChallengeResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FActivatePersonalChallengeDelegate Delegate) const;
    void OnCancelPersonalChallengeResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCancelPersonalChallengeDelegate Delegate) const;
    void OnClaimPersonalChallengeRewardResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FClaimPersonalChallengeRewardDelegate Delegate) const;
    void OnGenerateWebsocketAccessTokenResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGenerateWebsocketAccessTokenDelegate Delegate) const;
    void OnGetActivePersonalChallengesResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetActivePersonalChallengesDelegate Delegate) const;
    void OnGetAllPersonalChallengesResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetAllPersonalChallengesDelegate Delegate) const;
    void OnGetPersonalChallengeByIdResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetPersonalChallengeByIdDelegate Delegate) const;
    void OnGetPersonalChallengesResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetPersonalChallengesDelegate Delegate) const;
    void OnGetUnresolvedPersonalChallengesResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetUnresolvedPersonalChallengesDelegate Delegate) const;
    void OnUnlockPersonalChallengeResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnlockPersonalChallengeDelegate Delegate) const;
    
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
};
	
}
