/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiWrapper/ScillApiBaseModel.h"
#include "ScillApiWrapper/ScillApiBattlePassState.h"

namespace ScillSDK 
{

/*
 * ScillApiBattlePassExpiredPayload
 *
 * This object is sent via Webhook or notifications of type battlepass-expired.
 */
class SCILLSDK_API ScillApiBattlePassExpiredPayload : public Model
{
public:
    virtual ~ScillApiBattlePassExpiredPayload() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The type of the notification. If you receive this payload, it's most likely battlepass-expired */
	TOptional<FString> WebhookType;
	TOptional<ScillApiBattlePassState> OldBattlePass;
	TOptional<ScillApiBattlePassState> NewBattlePass;
};

}
