/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"

namespace ScillSDK
{

/*
 * ScillApiBattlePassChallengeState
 *
 * This object stores information about a battle pass challenge state. It is designed to update challenges loaded previously with the getBattlePassLevels API. Indices allow you to quickly update locally stored Challenge objects without iterating or reloading data.
 */
class SCILLSDK_API ScillApiBattlePassChallengeState : public Model
{
public:
    virtual ~ScillApiBattlePassChallengeState() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The unique id of the app */
	TOptional<FString> AppId;
	/* The unique id of this battle pass. */
	TOptional<FString> BattlePassId;
	/* Unique id of this BattlePassLevel object. */
	TOptional<FString> LevelId;
	/* This is your user id. You can set this to whatever you like, either your real user id or an obfuscated user id. However you need to be consistent here. Events linked to this user id only track if challenges or battle passes are unlocked with the same user id. */
	TOptional<FString> UserId;
	/* Typical usage pattern is to load battle pass levels with getBattlePassLevels operation and store them for rendering. Using this value you can quickly identify the index of the level that changed. */
	TOptional<int32> LevelPositionIndex;
	/* The unique id of this challenge. Every challenge is linked to a product. */
	TOptional<FString> ChallengeId;
	/* Same as level_position_index. Use this index to identify the challenge that changed within the levels challenges array. Typical usage pattern is to update the previously stored score and type. */
	TOptional<int32> ChallengePositionIndex;
	/* Indicates how many “tasks” must be completed or done to complete this challenge. */
	TOptional<int32> ChallengeGoal;
	/* Indicates how many tasks the user already has completed. Use this in combination with challenge_goal to render a nice progress bar. */
	TOptional<int32> UserChallengeCurrentScore;
	/* Indicates the status of the challenge. This can be one of the following unlock: Challenge does not track anything. in-progress: Challenge is active and tracking. overtime: User did not manage to finish the challenge in time. unclaimed: The challenge has been completed but the reward has not yet been claimed. finished: The challenge has been successfully be completed and the reward has been claimed */
	TOptional<FString> Type;
};

}
