/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"

namespace ScillSDK
{

/*
 * ScillApiBattlePassState
 *
 * This object holds some basic info about lifetime of a battle pass and is used in expired notifications.
 */
class SCILLSDK_API ScillApiBattlePassState : public Model
{
public:
    virtual ~ScillApiBattlePassState() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The unique id of this battle pass. */
	TOptional<FString> BattlePassId;
	/* The unique id of the app */
	TOptional<FString> AppId;
	/* The priority of the battle pass. I.e. if multiple are available you can use this field to sort them. */
	TOptional<int32> BattlePassPriority;
	/* The date (in iso format) when the Battle Pass starts. Tracking begins once this date is passed. */
	TOptional<FString> StartDate;
	/* The date (in iso format) when the Battle Pass ends. Tracking stops once the end is reached and users will not be able to progress further than what they have achieved up to that point. */
	TOptional<FString> EndDate;
	/* Indicated if this battle pass is active. */
	TOptional<bool> IsActive;
};

}
