/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"

namespace ScillSDK
{

/*
 * ScillApiEventProperty
 *
 * This object holds information about a proporty of an event. Events have required and optional properties.
 */
class SCILLSDK_API ScillApiEventProperty : public Model
{
public:
    virtual ~ScillApiEventProperty() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The name of the property. Is the field value in the event payloads meta_data. */
	TOptional<FString> PropertyName;
	/* The type of the property. Can be number or string. */
	TOptional<FString> PropertyType;
};

}
