/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"

namespace ScillSDK
{

/*
 * ScillApiBattlePass
 *
 * A Battle Pass is a structured layer above challenges and handles the lifecycle of challenges based on a level system. Users need to fullfil challenges to unlock the next level. Each level can have a reward that you can specify in the BattlePassLevel structure. Battle Passes need to be unlocked before they start tracking progress.
 */
class SCILLSDK_API ScillApiBattlePass : public Model
{
public:
    virtual ~ScillApiBattlePass() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The unique id of this battle pass. */
	TOptional<FString> BattlePassId;
	/* The unique id of the app */
	TOptional<FString> AppId;
	/* The name of the battle bass. You can set that in the Admin Panel. The language is set with the query parameter language. See documentation for more info on that. */
	TOptional<FString> BattlePassName;
	/* The description of the battle bass. You can set that in the Admin Panel and it can also be HTML. The language is set with the query parameter language. See documentation for more info on that. */
	TOptional<FString> BattlePassDescription;
	/* A short description of the battle bass. You can set that in the Admin Panel and it can also be HTML. The language is set with the query parameter language. See documentation for more info on that. */
	TOptional<FString> BattlePassShortDescription;
	/* Use this to provide some terms and conditions following along this battle passes purchase. */
	TOptional<FString> BattlePassDisclaimer;
	/* The priority of the battle pass. I.e. if multiple are available you can use this field to sort them. */
	TOptional<int32> BattlePassPriority;
	/* If you want to sell Battle Passes you can use this field to trigger in-app purchase products within your mobile app. You can set this value in the Admin Panel. This one is for iOS. */
	TOptional<FString> PackageSkuIos;
	/* If you want to sell Battle Passes you can use this field to trigger in-app purchase products within your mobile app. You can set this value in the Admin Panel. Use this to set the package string for Android. */
	TOptional<FString> PackageSkuAndroid;
	/* The xs sized image name or url. You can determine the best size distribution yourself and depends on your application or UI */
	TOptional<FString> ImageXs;
	/* The s sized image name or url. You can determine the best size distribution yourself and depends on your application or UI */
	TOptional<FString> ImageS;
	/* The m sized image name or url. You can determine the best size distribution yourself and depends on your application or UI */
	TOptional<FString> ImageM;
	/* The l sized image name or url. You can determine the best size distribution yourself and depends on your application or UI */
	TOptional<FString> ImageL;
	/* The xl sized image name or url. You can determine the best size distribution yourself and depends on your application or UI */
	TOptional<FString> ImageXl;
	/* The date (in iso format) when the Battle Pass starts. Tracking begins once this date is passed. */
	TOptional<FString> StartDate;
	/* The date (in iso format) when the Battle Pass ends. Tracking stops once the end is reached and users will not be able to progress further than what they have achieved up to that point. */
	TOptional<FString> EndDate;
	/* If the Battle Pass costs “money” you may want to route the user to a web site/page, where they can learn more about this battle pass. You can also use this field to route the user inside your application by providing a path or whatever works for you. */
	TOptional<FString> ReadMoreLink;
	/* Indicates if one level after the other must be activated or if users can activate whichever level they want. Typically battle passes are unlocked level by level, but if battle passes are used for other applications (like user referal programs) it can be useful to set this to false. */
	TOptional<bool> IsUnlockedIncrementally;
	/* Indicated if this battle pass is active. */
	TOptional<bool> IsActive;
	/* The date in iso format when the user unlocked this Battle Pass. */
	TOptional<FString> UnlockedAt;
	/* Indicates that this Battle Pass can be purchased via in-app purchase. This can be set in the Admin Panel. */
	TOptional<bool> CanPurchaseWithMoney;
	/* Indicates that this Battle Pass can be purchased with SCILL Coins. This can be set in the Admin Panel. */
	TOptional<bool> CanPurchaseWithCoins;
};

}
