/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"
#include "ScillApiLeaderboardV2Member.h"

namespace ScillSDK
{

/*
 * ScillApiLeaderboardV2MemberRanking
 *
 * The Leaderboard object contains information about the leaderboard itself like the name and the id
 */
class SCILLSDK_API ScillApiLeaderboardV2MemberRanking : public Model
{
public:
    virtual ~ScillApiLeaderboardV2MemberRanking() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The id of the leaderboard */
	TOptional<FString> LeaderboardId;
	/* The name of the leaderboard */
	TOptional<FString> LeaderboardName;
	/* Determines the results sort order. If true, the order is ascending, otherwise, it's descending. */
	TOptional<bool> LeaderboardSortOrderAscending;
	TOptional<ScillApiLeaderboardV2Member> LeaderboardMember;
};

}
