/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"

namespace ScillSDK
{

/*
 * ScillApiNotificationTopic
 *
 * Realtime updates are implemented via MQTT - a resource efficient real time message system. Each user has it&#39;s own channel in our MQTT system that you need to request from the backend. This structure returns the topic for the user provided with the access token.
 */
class SCILLSDK_API ScillApiNotificationTopic : public Model
{
public:
    virtual ~ScillApiNotificationTopic() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Topic;
};

}
