/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"
#include "ScillApiBattlePassLevelReward.h"

namespace ScillSDK
{

/*
 * ScillApiBattlePassLevelClaimedPayload
 *
 * Payload sent via Webhook or realtime notifications whenever a usrs level reward has been claimed. Use this payload to unlock the item for the specified user.
 */
class SCILLSDK_API ScillApiBattlePassLevelClaimedPayload : public Model
{
public:
    virtual ~ScillApiBattlePassLevelClaimedPayload() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The type of the notification. If you receive this payload, it's most likely battlepass-level-reward-claimed */
	TOptional<FString> WebhookType;
	TOptional<ScillApiBattlePassLevelReward> BattlePassLevelRewardClaimed;
};

}
