/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"
#include "ScillApiBattlePassChallengeState.h"

namespace ScillSDK
{

/*
 * ScillApiBattlePassChallengeChangedPayload
 *
 * This payload is sent in Webhooks and notifications as part of the battlepass-challenge-changed notification. The idea is to provide enough information to quickly update UI or implementing backend logic. We provide both the state of the object before it changed, and after that. This allows you to react in many different ways.
 */
class SCILLSDK_API ScillApiBattlePassChallengeChangedPayload : public Model
{
public:
    virtual ~ScillApiBattlePassChallengeChangedPayload() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The type of the notification. If you receive this payload, it's most likely battlepass-challenge-changed */
	TOptional<FString> WebhookType;
	TOptional<ScillApiBattlePassChallengeState> OldBattlePassChallenge;
	TOptional<ScillApiBattlePassChallengeState> NewBattlePassChallenge;
};

}
