/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"
#include "ScillApiLeaderboardsApi.h"

#include "ScillApiActionResponse.h"
#include "ScillApiError.h"
#include "ScillApiLeaderboard.h"
#include "ScillApiLeaderboardMemberRanking.h"

namespace ScillSDK
{

/* Retrieve Leaderboard
 *
 * Provides the current leaderboard rankings for a specific leaderboard.
*/
class SCILLSDK_API ScillApiLeaderboardsApi::GetLeaderboardRequest : public Request
{
public:
    virtual ~GetLeaderboardRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The id of the leaderboard */
	FString LeaderboardId;
	/* The page index starting at 1. The number of pageSize elements are returned for each page. Default value is 1 */
	TOptional<int32> CurrentPage;
	/* The number of elements per page. Default is 25. */
	TOptional<int32> PageSize;
	/* The starting date for fetching results. */
	TOptional<FString> StartDate;
	/* The ending date for fetching results. */
	TOptional<FString> EndDate;
	/* Set the language. Content can be translated in the Admin Panel. Values can be international language codes like de, en, fr, it, ... */
	TOptional<FString> Language;
};

class SCILLSDK_API ScillApiLeaderboardsApi::GetLeaderboardResponse : public Response
{
public:
    virtual ~GetLeaderboardResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ScillApiLeaderboard Content;
};

/* Retrieve User Ranking
 *
 * Returns a LeaderboardMemberRanking item for the specified leaderboard. Use this route to get the position of a user of team in a specified leaderboard.
*/
class SCILLSDK_API ScillApiLeaderboardsApi::GetLeaderboardRankingRequest : public Request
{
public:
    virtual ~GetLeaderboardRankingRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The member type, can be user or team (right now) and sets which leaderboards should be selected. */
	FString MemberType;
	/* Either the user_id or team_id you used when sending the events. The memberType flag identifies which one is used. */
	FString MemberId;
	/* The id of the leaderboard */
	FString LeaderboardId;
	/* The starting date for fetching results. */
	TOptional<FString> StartDate;
	/* The ending date for fetching results. */
	TOptional<FString> EndDate;
	/* Set the language. Content can be translated in the Admin Panel. Values can be international language codes like de, en, fr, it, ... */
	TOptional<FString> Language;
};

class SCILLSDK_API ScillApiLeaderboardsApi::GetLeaderboardRankingResponse : public Response
{
public:
    virtual ~GetLeaderboardRankingResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ScillApiLeaderboardMemberRanking Content;
};

/* Retrieve User Rankings
 *
 * Returns an array of LeaderboardRanking items defined for all leaderboards in the application specified for the user. If the member is not in the leaderboard, the rank will be -1 in the LeaderboardRanking object.
*/
class SCILLSDK_API ScillApiLeaderboardsApi::GetLeaderboardRankingsRequest : public Request
{
public:
    virtual ~GetLeaderboardRankingsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The member type, can be user or team (right now) and sets which leaderboards should be selected. */
	FString MemberType;
	/* Either the user_id or team_id you used when sending the events. The memberType flag identifies which one is used. */
	FString MemberId;
	/* The starting date for fetching results. */
	TOptional<FString> StartDate;
	/* The ending date for fetching results. */
	TOptional<FString> EndDate;
	/* Set the language. Content can be translated in the Admin Panel. Values can be international language codes like de, en, fr, it, ... */
	TOptional<FString> Language;
};

class SCILLSDK_API ScillApiLeaderboardsApi::GetLeaderboardRankingsResponse : public Response
{
public:
    virtual ~GetLeaderboardRankingsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TArray<ScillApiLeaderboardMemberRanking> Content;
};

/* Retrieve Leaderboards
 *
 * Returns an array of Leaderboard items defined for the application.
*/
class SCILLSDK_API ScillApiLeaderboardsApi::GetLeaderboardsRequest : public Request
{
public:
    virtual ~GetLeaderboardsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The page index starting at 1. The number of pageSize elements are returned for each page. Default value is 1 */
	TOptional<int32> CurrentPage;
	/* The number of elements per page. Default is 25. */
	TOptional<int32> PageSize;
	/* The starting date for fetching results. */
	TOptional<FString> StartDate;
	/* The ending date for fetching results. */
	TOptional<FString> EndDate;
	/* Set the language. Content can be translated in the Admin Panel. Values can be international language codes like de, en, fr, it, ... */
	TOptional<FString> Language;
};

class SCILLSDK_API ScillApiLeaderboardsApi::GetLeaderboardsResponse : public Response
{
public:
    virtual ~GetLeaderboardsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TArray<ScillApiLeaderboard> Content;
};

/* Reset user leaderboard data
 *
 * Delete all leaderboard data, i.e. reset the leaderboard for the specified member.
*/
class SCILLSDK_API ScillApiLeaderboardsApi::ResetLeaderboardRankingsRequest : public Request
{
public:
    virtual ~ResetLeaderboardRankingsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The member type, can be user or team (right now) and sets which leaderboards should be selected. */
	FString MemberType;
	/* The application ID */
	FString AppId;
	/* Either the user_id or team_id you used when sending the events. The memberType flag identifies which one is used. */
	FString MemberId;
};

class SCILLSDK_API ScillApiLeaderboardsApi::ResetLeaderboardRankingsResponse : public Response
{
public:
    virtual ~ResetLeaderboardRankingsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ScillApiActionResponse Content;
};

}
