/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"
#include "ScillApiLeaderboardV2Info.h"

namespace ScillSDK
{

/*
 * ScillApiLeaderboardV2Changed
 *
 * This object is sent via Webhook or notifications of type leaderboard-changed.
 */
class SCILLSDK_API ScillApiLeaderboardV2Changed : public Model
{
public:
    virtual ~ScillApiLeaderboardV2Changed() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The type of the notification. If you receive this payload, it's most likely leaderboard-changed. */
	TOptional<FString> WebhookType;
	TOptional<ScillApiLeaderboardV2Info> OldLeaderboard;
	TOptional<ScillApiLeaderboardV2Info> NewLeaderboard;
};

}
