/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"

namespace ScillSDK
{

/*
 * ScillApiUserInfo
 *
 * Can be any object that is attached to the user. You can set these values in the user service. For example you can provide a user name and an avatar image url.
 */
class SCILLSDK_API ScillApiUserInfo : public Model
{
public:
    virtual ~ScillApiUserInfo() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The user name of the user */
	TOptional<FString> Username;
	/* The name or URL of an avatar image for a user. */
	TOptional<FString> AvatarImage;
};

}
