/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ScillApiBaseModel.h"

namespace ScillSDK
{

/*
 * ScillApiBattlePassTranslation
 *
 * 
 */
class SCILLSDK_API ScillApiBattlePassTranslation : public Model
{
public:
    virtual ~ScillApiBattlePassTranslation() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The id of the language */
	TOptional<FString> LanguageId;
	/* The name of the Battle Pass in the local language set in the request (see Setting Language). In the admin panel you can either create HTML content or plain text. */
	TOptional<FString> Name;
	/* The description of the Battle Pass in the local language set in the request (see Setting Language). In the admin panel you can either create HTML content or plain text. */
	TOptional<FString> Description;
	/* A short description in the local language you can use to teaser battle passes or implement “expand for more” functionality. */
	TOptional<FString> ShortDescription;
	/* Use this to provide some terms and conditions following along this battle passes purchase. */
	TOptional<FString> Disclaimer;
};

}
