/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ScillApiWrapper/ScillApiBattlePassUnlockInfo.h"

#include "ScillSDKModule.h"
#include "ScillApiWrapper/ScillApiHelpers.h"

#include "Templates/SharedPointer.h"

namespace ScillSDK
{

void ScillApiBattlePassUnlockInfo::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (PurchaseId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("purchase_id")); WriteJsonValue(Writer, PurchaseId.GetValue());
	}
	if (BattlePassId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("battle_pass_id")); WriteJsonValue(Writer, BattlePassId.GetValue());
	}
	if (UserId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("user_id")); WriteJsonValue(Writer, UserId.GetValue());
	}
	if (PurchasePrice.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("purchase_price")); WriteJsonValue(Writer, PurchasePrice.GetValue());
	}
	if (PurchaseCurrency.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("purchase_currency")); WriteJsonValue(Writer, PurchaseCurrency.GetValue());
	}
	if (PurchasedAt.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("purchased_at")); WriteJsonValue(Writer, PurchasedAt.GetValue());
	}
	if (BattlePassCompleted.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("battle_pass_completed")); WriteJsonValue(Writer, BattlePassCompleted.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool ScillApiBattlePassUnlockInfo::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("purchase_id"), PurchaseId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("battle_pass_id"), BattlePassId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("user_id"), UserId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("purchase_price"), PurchasePrice);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("purchase_currency"), PurchaseCurrency);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("purchased_at"), PurchasedAt);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("battle_pass_completed"), BattlePassCompleted);

	return ParseSuccess;
}

}
