/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ScillApiWrapper/ScillApiLeaderboardUpdatePayload.h"

#include "ScillSDKModule.h"
#include "ScillApiWrapper/ScillApiHelpers.h"

#include "Templates/SharedPointer.h"

namespace ScillSDK
{

void ScillApiLeaderboardUpdatePayload::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (WebhookType.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("webhook_type")); WriteJsonValue(Writer, WebhookType.GetValue());
	}
	if (LeaderboardData.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("leaderboard_data")); WriteJsonValue(Writer, LeaderboardData.GetValue());
	}
	if (MemberData.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("member_data")); WriteJsonValue(Writer, MemberData.GetValue());
	}
	if (OldLeaderboardRanking.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("old_leaderboard_ranking")); WriteJsonValue(Writer, OldLeaderboardRanking.GetValue());
	}
	if (NewLeaderboardRanking.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("new_leaderboard_ranking")); WriteJsonValue(Writer, NewLeaderboardRanking.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool ScillApiLeaderboardUpdatePayload::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("webhook_type"), WebhookType);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("leaderboard_data"), LeaderboardData);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("member_data"), MemberData);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("old_leaderboard_ranking"), OldLeaderboardRanking);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("new_leaderboard_ranking"), NewLeaderboardRanking);

	return ParseSuccess;
}

}
