/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ScillApiWrapper/ScillApiBattlePassState.h"

#include "ScillSDKModule.h"
#include "ScillApiWrapper/ScillApiHelpers.h"

#include "Templates/SharedPointer.h"

namespace ScillSDK
{

void ScillApiBattlePassState::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (BattlePassId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("battle_pass_id")); WriteJsonValue(Writer, BattlePassId.GetValue());
	}
	if (AppId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("app_id")); WriteJsonValue(Writer, AppId.GetValue());
	}
	if (BattlePassPriority.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("battle_pass_priority")); WriteJsonValue(Writer, BattlePassPriority.GetValue());
	}
	if (StartDate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("start_date")); WriteJsonValue(Writer, StartDate.GetValue());
	}
	if (EndDate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("end_date")); WriteJsonValue(Writer, EndDate.GetValue());
	}
	if (IsActive.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("is_active")); WriteJsonValue(Writer, IsActive.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool ScillApiBattlePassState::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("battle_pass_id"), BattlePassId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("app_id"), AppId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("battle_pass_priority"), BattlePassPriority);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("start_date"), StartDate);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("end_date"), EndDate);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("is_active"), IsActive);

	return ParseSuccess;
}

}
