/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ScillApiWrapper/ScillApiChallenge.h"

#include "ScillSDKModule.h"
#include "ScillApiWrapper/ScillApiHelpers.h"

#include "Templates/SharedPointer.h"

namespace ScillSDK
{

void ScillApiChallenge::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (ChallengeId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_id")); WriteJsonValue(Writer, ChallengeId.GetValue());
	}
	if (ChallengeName.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_name")); WriteJsonValue(Writer, ChallengeName.GetValue());
	}
	if (ChallengeDescription.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_description")); WriteJsonValue(Writer, ChallengeDescription.GetValue());
	}
	if (ChallengeDurationTime.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_duration_time")); WriteJsonValue(Writer, ChallengeDurationTime.GetValue());
	}
	if (LiveDate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("live_date")); WriteJsonValue(Writer, LiveDate.GetValue());
	}
	if (ChallengeGoal.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_goal")); WriteJsonValue(Writer, ChallengeGoal.GetValue());
	}
	if (UserChallengeCurrentScore.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("user_challenge_current_score")); WriteJsonValue(Writer, UserChallengeCurrentScore.GetValue());
	}
	if (ChallengeIcon.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_icon")); WriteJsonValue(Writer, ChallengeIcon.GetValue());
	}
	if (ChallengeIconHd.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_icon_hd")); WriteJsonValue(Writer, ChallengeIconHd.GetValue());
	}
	if (ChallengePrice.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_price")); WriteJsonValue(Writer, ChallengePrice.GetValue());
	}
	if (ChallengeReward.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_reward")); WriteJsonValue(Writer, ChallengeReward.GetValue());
	}
	if (ChallengeRewardType.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_reward_type")); WriteJsonValue(Writer, ChallengeRewardType.GetValue());
	}
	if (ChallengeGoalCondition.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_goal_condition")); WriteJsonValue(Writer, ChallengeGoalCondition.GetValue());
	}
	if (ChallengeXp.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_xp")); WriteJsonValue(Writer, ChallengeXp.GetValue());
	}
	if (Repeatable.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("repeatable")); WriteJsonValue(Writer, Repeatable.GetValue());
	}
	if (Type.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type.GetValue());
	}
	if (ChallengeAutoActivated.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("challenge_auto_activated")); WriteJsonValue(Writer, ChallengeAutoActivated.GetValue());
	}
	if (IsClaimed.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("is_claimed")); WriteJsonValue(Writer, IsClaimed.GetValue());
	}
	if (UserChallengeUnlockedAt.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("user_challenge_unlocked_at")); WriteJsonValue(Writer, UserChallengeUnlockedAt.GetValue());
	}
	if (UserChallengeActivatedAt.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("user_challenge_activated_at")); WriteJsonValue(Writer, UserChallengeActivatedAt.GetValue());
	}
	if (UserChallengeIsClaimed.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("user_challenge_is_claimed")); WriteJsonValue(Writer, UserChallengeIsClaimed.GetValue());
	}
	if (UserChallengeStatus.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("user_challenge_status")); WriteJsonValue(Writer, UserChallengeStatus.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool ScillApiChallenge::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_id"), ChallengeId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_name"), ChallengeName);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_description"), ChallengeDescription);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_duration_time"), ChallengeDurationTime);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("live_date"), LiveDate);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_goal"), ChallengeGoal);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("user_challenge_current_score"), UserChallengeCurrentScore);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_icon"), ChallengeIcon);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_icon_hd"), ChallengeIconHd);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_price"), ChallengePrice);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_reward"), ChallengeReward);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_reward_type"), ChallengeRewardType);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_goal_condition"), ChallengeGoalCondition);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_xp"), ChallengeXp);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("repeatable"), Repeatable);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("type"), Type);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("challenge_auto_activated"), ChallengeAutoActivated);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("is_claimed"), IsClaimed);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("user_challenge_unlocked_at"), UserChallengeUnlockedAt);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("user_challenge_activated_at"), UserChallengeActivatedAt);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("user_challenge_is_claimed"), UserChallengeIsClaimed);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("user_challenge_status"), UserChallengeStatus);

	return ParseSuccess;
}

}
