/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ScillApiWrapper/ScillApiBattlePassTranslation.h"

#include "ScillSDKModule.h"
#include "ScillApiWrapper/ScillApiHelpers.h"

#include "Templates/SharedPointer.h"

namespace ScillSDK
{

void ScillApiBattlePassTranslation::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (LanguageId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("language_id")); WriteJsonValue(Writer, LanguageId.GetValue());
	}
	if (Name.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name.GetValue());
	}
	if (Description.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("description")); WriteJsonValue(Writer, Description.GetValue());
	}
	if (ShortDescription.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("short_description")); WriteJsonValue(Writer, ShortDescription.GetValue());
	}
	if (Disclaimer.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("disclaimer")); WriteJsonValue(Writer, Disclaimer.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool ScillApiBattlePassTranslation::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("language_id"), LanguageId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("description"), Description);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("short_description"), ShortDescription);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("disclaimer"), Disclaimer);

	return ParseSuccess;
}

}
