/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ScillApiWrapper/ScillApiLeaderboardsV2Api.h"

#include "ScillApiWrapper/ScillApiLeaderboardsV2ApiOperations.h"
#include "ScillSDKModule.h"

#include "HttpModule.h"
#include "Serialization/JsonSerializer.h"

namespace ScillSDK
{

ScillApiLeaderboardsV2Api::ScillApiLeaderboardsV2Api()
: Url(TEXT("https://virtserver.swaggerhub.com/4Players-GmbH/scill-gaas/1.0.0"))
{
}

ScillApiLeaderboardsV2Api::~ScillApiLeaderboardsV2Api() {}

void ScillApiLeaderboardsV2Api::SetURL(const FString& InUrl)
{
	Url = InUrl;
}

void ScillApiLeaderboardsV2Api::AddHeaderParam(const FString& Key, const FString& Value)
{
	AdditionalHeaderParams.Add(Key, Value);
}

void ScillApiLeaderboardsV2Api::ClearHeaderParams()
{
	AdditionalHeaderParams.Reset();
}

bool ScillApiLeaderboardsV2Api::IsValid() const
{
	if (Url.IsEmpty())
	{
		UE_LOG(LogScillSDK, Error, TEXT("ScillApiLeaderboardsV2Api: Endpoint Url is not set, request cannot be performed"));
		return false;
	}

	return true;
}

void ScillApiLeaderboardsV2Api::SetHttpRetryManager(FHttpRetrySystem::FManager& InRetryManager)
{
	if(RetryManager != &GetHttpRetryManager())
	{
		DefaultRetryManager.Reset();
		RetryManager = &InRetryManager;
	}
}

FHttpRetrySystem::FManager& ScillApiLeaderboardsV2Api::GetHttpRetryManager()
{
	checkf(RetryManager, TEXT("ScillApiLeaderboardsV2Api: RetryManager is null.  You may have meant to set it with SetHttpRetryManager first, or you may not be using a custom RetryManager at all."))
	return *RetryManager;
}

FHttpRequestRef ScillApiLeaderboardsV2Api::CreateHttpRequest(const Request& Request) const
{
	if (!Request.GetRetryParams().IsSet())
	{
		return FHttpModule::Get().CreateRequest();
	}
	else
	{
		if (!RetryManager)
		{
			// Create default retry manager if none was specified
			DefaultRetryManager = MakeUnique<HttpRetryManager>(6, 60);
			RetryManager = DefaultRetryManager.Get();
		}

		const HttpRetryParams& Params = Request.GetRetryParams().GetValue();
		return RetryManager->CreateRequest(Params.RetryLimitCountOverride, Params.RetryTimeoutRelativeSecondsOverride, Params.RetryResponseCodes, Params.RetryVerbs, Params.RetryDomains);
	}
}

void ScillApiLeaderboardsV2Api::HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const
{
	InOutResponse.SetHttpResponse(HttpResponse);
	InOutResponse.SetSuccessful(bSucceeded);

	if (bSucceeded && HttpResponse.IsValid())
	{
		InOutResponse.SetHttpResponseCode((EHttpResponseCodes::Type)HttpResponse->GetResponseCode());
		FString ContentType = HttpResponse->GetContentType();
		FString Content;

		if (ContentType.IsEmpty())
		{
			return; // Nothing to parse
		}
		else if (ContentType.StartsWith(TEXT("application/json")) || ContentType.StartsWith("text/json"))
		{
			Content = HttpResponse->GetContentAsString();

			TSharedPtr<FJsonValue> JsonValue;
			auto Reader = TJsonReaderFactory<>::Create(Content);

			if (FJsonSerializer::Deserialize(Reader, JsonValue) && JsonValue.IsValid())
			{
				if (InOutResponse.FromJson(JsonValue))
					return; // Successfully parsed
			}
		}
		else if(ContentType.StartsWith(TEXT("text/plain")))
		{
			Content = HttpResponse->GetContentAsString();
			InOutResponse.SetResponseString(Content);
			return; // Successfully parsed
		}

		// Report the parse error but do not mark the request as unsuccessful. Data could be partial or malformed, but the request succeeded.
		UE_LOG(LogScillSDK, Error, TEXT("Failed to deserialize Http response content (type:%s):\n%s"), *ContentType , *Content);
		return;
	}

	// By default, assume we failed to establish connection
	InOutResponse.SetHttpResponseCode(EHttpResponseCodes::RequestTimeout);
}

FHttpRequestPtr ScillApiLeaderboardsV2Api::GetLeaderboardV2(const GetLeaderboardV2Request& Request, const FGetLeaderboardV2Delegate& Delegate /*= FGetLeaderboardV2Delegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ScillApiLeaderboardsV2Api::OnGetLeaderboardV2Response, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ScillApiLeaderboardsV2Api::OnGetLeaderboardV2Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetLeaderboardV2Delegate Delegate) const
{
	GetLeaderboardV2Response Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ScillApiLeaderboardsV2Api::GetLeaderboardV2Ranking(const GetLeaderboardV2RankingRequest& Request, const FGetLeaderboardV2RankingDelegate& Delegate /*= FGetLeaderboardV2RankingDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ScillApiLeaderboardsV2Api::OnGetLeaderboardV2RankingResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ScillApiLeaderboardsV2Api::OnGetLeaderboardV2RankingResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetLeaderboardV2RankingDelegate Delegate) const
{
	GetLeaderboardV2RankingResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ScillApiLeaderboardsV2Api::GetLeaderboardV2Rankings(const GetLeaderboardV2RankingsRequest& Request, const FGetLeaderboardV2RankingsDelegate& Delegate /*= FGetLeaderboardV2RankingsDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ScillApiLeaderboardsV2Api::OnGetLeaderboardV2RankingsResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ScillApiLeaderboardsV2Api::OnGetLeaderboardV2RankingsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetLeaderboardV2RankingsDelegate Delegate) const
{
	GetLeaderboardV2RankingsResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ScillApiLeaderboardsV2Api::GetLeaderboardsV2(const GetLeaderboardsV2Request& Request, const FGetLeaderboardsV2Delegate& Delegate /*= FGetLeaderboardsV2Delegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ScillApiLeaderboardsV2Api::OnGetLeaderboardsV2Response, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ScillApiLeaderboardsV2Api::OnGetLeaderboardsV2Response(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetLeaderboardsV2Delegate Delegate) const
{
	GetLeaderboardsV2Response Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr ScillApiLeaderboardsV2Api::ResetLeaderboardV2Rankings(const ResetLeaderboardV2RankingsRequest& Request, const FResetLeaderboardV2RankingsDelegate& Delegate /*= FResetLeaderboardV2RankingsDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ScillApiLeaderboardsV2Api::OnResetLeaderboardV2RankingsResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void ScillApiLeaderboardsV2Api::OnResetLeaderboardV2RankingsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FResetLeaderboardV2RankingsDelegate Delegate) const
{
	ResetLeaderboardV2RankingsResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

}
