/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ScillApiWrapper/ScillApiLeaderboardV2MemberRanking.h"

#include "ScillSDKModule.h"
#include "ScillApiWrapper/ScillApiHelpers.h"

#include "Templates/SharedPointer.h"

namespace ScillSDK
{

void ScillApiLeaderboardV2MemberRanking::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (LeaderboardId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("leaderboard_id")); WriteJsonValue(Writer, LeaderboardId.GetValue());
	}
	if (LeaderboardName.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("leaderboard_name")); WriteJsonValue(Writer, LeaderboardName.GetValue());
	}
	if (LeaderboardSortOrderAscending.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("leaderboard_sort_order_ascending")); WriteJsonValue(Writer, LeaderboardSortOrderAscending.GetValue());
	}
	if (LeaderboardMember.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("leaderboard_member")); WriteJsonValue(Writer, LeaderboardMember.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool ScillApiLeaderboardV2MemberRanking::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("leaderboard_id"), LeaderboardId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("leaderboard_name"), LeaderboardName);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("leaderboard_sort_order_ascending"), LeaderboardSortOrderAscending);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("leaderboard_member"), LeaderboardMember);

	return ParseSuccess;
}

}
