/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ScillApiWrapper/ScillApiChallengeWebhookPayload.h"

#include "ScillSDKModule.h"
#include "ScillApiWrapper/ScillApiHelpers.h"

#include "Templates/SharedPointer.h"

namespace ScillSDK
{

void ScillApiChallengeWebhookPayload::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (WebhookType.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("webhook_type")); WriteJsonValue(Writer, WebhookType.GetValue());
	}
	if (CategoryPosition.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("category_position")); WriteJsonValue(Writer, CategoryPosition.GetValue());
	}
	if (UserToken.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("user_token")); WriteJsonValue(Writer, UserToken.GetValue());
	}
	if (NewChallenge.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("new_challenge")); WriteJsonValue(Writer, NewChallenge.GetValue());
	}
	if (OldChallenge.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("old_challenge")); WriteJsonValue(Writer, OldChallenge.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool ScillApiChallengeWebhookPayload::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("webhook_type"), WebhookType);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("category_position"), CategoryPosition);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("user_token"), UserToken);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("new_challenge"), NewChallenge);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("old_challenge"), OldChallenge);

	return ParseSuccess;
}

}
